### ISSUE TITLE
Path is not expanded

### ISSUE THREAD

**Issue by rsteube** [kevincox/rustymedia#10] opened 2019-08-09 23:00 UTC
When using `~` as in the example `--local 'My Videos'=~/Videos` no content is listed.
Absolute path works.

**Comment by kevincox** [comment] 2019-08-10 08:29
Path expansion is the job of the shell, not the program. I would check if your shell has options to expand paths after an `=` or if you can manually expand the path. You can also use `$HOME/Videos`. 

I'm closing because this is working as intended.

**Closed as completed by kevincox** 2019-08-10 08:29 UTC

**Comment by rsteube** [comment] 2019-08-10 10:00
My bad, yes it works in bash. For zsh i need to enable `magicequalsubst` :https://unix.stackexchange.com/a/373532
